# ─── NETWORK ────────────────────────────────────────────────────────
bind 0.0.0.0
port 6379
protected-mode yes
#Defines pending connection queue size.
tcp-backlog 511 
timeout 300
tcp-keepalive 60

# ─── AUTH ───────────────────────────────────────────────────────────

# ─── MEMORY ─────────────────────────────────────────────────────────
# Tuned for OTP (short TTL) + rate limiting (sliding window counters)
maxmemory 256mb
# evict only keys WITH expiry (OTPs, counters)
maxmemory-policy volatile-lru        
maxmemory-samples 10

# ─── PERSISTENCE ─────────────────────────────────────────────────────
# OTP/rate-limit data is ephemeral — disable RDB snapshots
save ""
appendonly no

# ─── LOGGING ────────────────────────────────────────────────────────
loglevel notice
#default logging in file /var/log/redis/redis.log
logfile "" 

# ─── PERFORMANCE ─────────────────────────────────────────────────────
# faster key expiry (important for OTP TTLs)
hz 20                               
dynamic-hz yes
# non-blocking key deletion on expiry (Deletion happens asynchronously.)
lazyfree-lazy-expire yes            
lazyfree-lazy-eviction yes

# ─── SECURITY ────────────────────────────────────────────────────────
# disable dangerous commands #FLUSHALL Deletes all keys in Redis.
# rename-command FLUSHALL  ""     
# #FLUSHDB. Deletes entire database.    
# rename-command FLUSHDB   ""          
# rename-command DEBUG     ""
# rename-command CONFIG    "CONFIG_PROD_ONLY"

# ─── SLOW LOG ────────────────────────────────────────────────────────
# log queries > 10ms
slowlog-log-slower-than 10000       
slowlog-max-len 128