services:
  fastapi:
    image: naman/fastapi-api:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fast_api_server
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size : "10m"
        max-file : "3"

    healthcheck:
      test : ["CMD","curl","-f","http://localhost:8000/api/v1/health/live"]
      interval: 30s
      timeout: 5s
      retries: 2

    networks:
      - backend
    
  redis:
    image:  naman/redis_db:1.0 
    build:
      context: .
      dockerfile: docker/redis/Dockerfile.redis
    container_name: redis_server
    command: ["--requirepass", "${REDIS_PSWD}"]
    ports:
      - "127.0.0.1:6379:6379"
    env_file:
      - .env
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-file : "2"
        max-size : "5m"
    # volumes:
    #   - redis_data:/data #persist redis data (data folder mount point and redis_data is volume)
    healthcheck:
      test : ["CMD", "redis-cli", "-a", "${REDIS_PSWD}", "ping"]
      interval: 5s
      timeout: 3s 
      retries: 3
    restart: unless-stopped
  
  scheduler:
    image: naman/scheduler:1.0
    build: 
      context: .
      dockerfile: docker/scheduler/Dockerfile
    networks:
      - backend
    env_file:
      - .env
    healthcheck:
      test : ["CMD-SHELL", "find /tmp/scheduler_heartbeat -mmin -45 | grep -q ."]
      interval: 30m
      timeout: 10s
      retries: 2
      start_period: 35m # grace period — first run hasn't happened yet at container start
    restart: unless-stopped

networks:
  backend : 
    driver: bridge #by default it is bridge



