"""refresh session model

Revision ID: a491642dfc8e
Revises: e6ff859f1c07
Create Date: 2026-03-04 17:13:20.782449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a491642dfc8e'
down_revision: Union[str, Sequence[str], None] = 'e6ff859f1c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_sessions', sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('refresh_sessions', sa.Column('replaced_by_token_id', sa.UUID(), nullable=True))
    op.alter_column('refresh_sessions', 'hashed_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.create_index('idx_refresh_absolute_expiry', 'refresh_sessions', ['absolute_expires_at'], unique=False)
    op.create_unique_constraint(None, 'refresh_sessions', ['hashed_token'])
    op.create_foreign_key(None, 'refresh_sessions', 'refresh_sessions', ['replaced_by_token_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_constraint(None, 'refresh_sessions', type_='foreignkey')
    op.drop_constraint(None, 'refresh_sessions', type_='unique')
    op.drop_index('idx_refresh_absolute_expiry', table_name='refresh_sessions')
    op.alter_column('refresh_sessions', 'hashed_token',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('refresh_sessions', 'replaced_by_token_id')
    op.drop_column('refresh_sessions', 'absolute_expires_at')
    # ### end Alembic commands ###
