"""add role enum properly and new fields

Revision ID: d81fb5f07a2b
Revises: d5a36720803a
Create Date: 2026-02-19 15:44:49.876830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd81fb5f07a2b'
down_revision: Union[str, Sequence[str], None] = 'd5a36720803a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'user', name='userrole', native_enum=False), nullable=False))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('users', 'role')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
